version: '3.5'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=C0ntrol1*
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer